### ISSUE TITLE
sshd fails to open binary as user shell

### ISSUE THREAD

**Issue by cross** [BrunoBonacci/lein-binplus#2]
If you use one of the generated binaries as a shell for a user, when you try to log in as that user (on Linux, via ssh), the login will fail saying:

```
Last login: Tue Jan 31 14:59:21 2017 from 10.151.38.57
/bin/thing: Exec format error
```

Googling around, specifically finding [http://skife.org/java/unix/2011/06/20/really_executable_jars.html](http://skife.org/java/unix/2011/06/20/really_executable_jars.html), I found that simply pre-pending "#!/bin/sh" (and a line-break, which may or may not be required) to the binary will cause the exec contained within to work.  Now, this would not work on Windows, I'm sure, but.

Adding this into `jar-preamble` would work for Linux (and Mac OS X), but would break Windows.  I just need it for Linux, myself, but.

**Comment by BrunoBonacci** [comment]
Hi @cross,

unfortunately your solution is not cross platform as you suggested, I can't include this in the main release.

However I've added the possibility to provide a custom preamble so that we accommodate your requirement.

For example in your `project.clj` you could add

```
:bin {:name "my-bin" 
      :bootclasspath false 
      :custom-preamble "#!/bin/sh\nexec java -jar $0 \"$@\"\n" }
```

Please use the following version `[lein-binplus "0.5.0-SNAPSHOT"]` which contains this change.
If this is good enough for you, I'll make an official release.

**Comment by cross** [comment]
Okay.  I'd also been thinking about a boolean flag to ask for the special extra-UNIX version and having that as an option in the code.  But, your solution is likely better.  If you provided a boolean, though, you could avoid the whole call into `sanitize-jvm-opts-for-win`.  Did you do anything to avoid some of the processing in the code if a custom-preamble is provided?

Also, this invalidates the use of bootclasspath, correct?

**Comment by cross** [comment]
Okay.  Following on from the earlier comment, I think this leaves too much undone.  I think it may need a way to embed the flags and/or other pieces (bootclasspath differences?) into the given custom string.  Ignoring the bootclasspath issue, I see the following from lein-binplus when I don't specify a `custom-preamble`:

```
:;exec java -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:-OmitStackTraceInFastThrow -client -Dtbx.version=0.1.0-SNAPSHOT -jar $0 "$@"
@echo off
java -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:-OmitStackTraceInFastThrow -client -Dtbx.version=0.1.0-SNAPSHOT -jar %1 "%~f0" %*
goto :eof
```

but, with the given example of your custom-preamble, I see as you'd expect:

```
#!/bin/sh
exec java -jar $0 "$@" 
```

Does it seem reasonable to allow a field for replacement of flags?  Any idea of a way to allow `custom-preamble` to coexist with `bootclasspath`?  The latter I guess is far less significant, since that's doable manually.  The former, however, I think will be needed for this to be generally useful.

**Comment by BrunoBonacci** [comment]
Hi,
The point is that `custom-preamble` allows you to overrides the default production of a preamble.
If you want the bootclasspath option you can just add `-Xbootclasspath/a:$0`.
Regarding the `-XX:+TieredCompilation -XX:TieredStopAtLevel=1` flags, these shouldn't be used for a production. In practice you are telling the JVM to never use the JIT compiler optimizations and always run in interpreted mode.
Finally you could pass external flags into your app by specifying them like:

```
#!/bin/sh
exec java -server -Xmx1G -XX:+UseG1GC $JVM_OPTS -jar $0 "$@" 
```

In this way you can set the environment variable `JVM_OPTS` in the caller and have your options added to the java line.

The only part it is left out is the the version property `-Dtbx.version=0.1.0-SNAPSHOT`.

**Comment by cross** [comment]
Well, the point was not the particular options in my example, but that the build process (whether lein or maven) passed those arguments into the system.  I didn’t specify them, at least not for this individual protect, they may’ve come from higher up in the source tree.  I am unfortunately not very knowledgeable about these systems, just helping out on this edge case we’ve found.

And, as the original problem I’m trying to solve is to have sshd invoke this as a login shell for a user, setting environment variables before running the program is not an available option.

What I was hoping is that I could allow leiningen to do what it was already doing, and provide those pieces for me, and I could include them.  Supplying instead a template, rather than a hard and unchangeable string.  Then, it would be able to pass all of those things in for me without me having to hard-code effectively variables controlled by the build system into this uncontrolled string.  We could do something even more complicated, with prefixes, and suffixes, and stuff.  But I think just a template would be easier.  And yes, I agree that nor supporting bootclasspath is acceptable.  I’d _like_ to be able to do that, so I could again allow leiningen to supply the correct main, rather than having to hard-code it in the string, but that’s much less of an issue than the other flags being built by leiningen (and/or maven).

Hopefully, you can understand my thinking here.

**Comment by BrunoBonacci** [comment]
Hi @cross,
I got what you mean, however what you asking is not much different that what you can do with the custom-preamble. 

The JVM options mentioned above they come from leiningen. Leiningen has a project property called `:jvm-opts` in which you can list the JVM option to pass to the child process when running `lein run` or `lein repl`. If not provided it default to the options in your message.
_These options are only interesting for development and shouldn't be used for production runtime._

Additionally since this `:jvm-opts` must be part of your `project.clj` you can control them directly.
The issue with the template is that it is very hard to combine a custom provided template with the multi-platform nature of the plugin. Different OS have different capabilities and it is hard to be generic.

I believe that with the `:custom-preamble` you can achieve your goal and generate an executable jar which runs in your particular scenario. Whether you set all your options directly in the project.clj (which i would recommend in your case) or let them flow from an external system doesn't really matter. The point is that you have a way to craft all the required options.

Another important part is the java path. Depending on the system, but it might be necessary for your to specify the full path of your java executable. With custom-preamble you can, and you can craft it to the need of your specific system.

However if you think that the same result could be achieved with a template maintaining the multi-platform capabilities, then I would be happy to accept a pull request ;-)

**Comment by cross** [comment]
I accept that using a custom preamble, at least as I plan to, does eliminate the multi-platform capabilities.  I have no desire to change the default behavior, because I don't have the ability to test multiple platforms to maintain that.  Which is why I was only looking at changing this newly added piece.

But, I think enhancing the `custom-preamble` to have a couple fields that can be substituted from the parameters that come in would be beneficial.  I'm experimenting now, and was just thinking I would fork and send you a pull request when I have something I like.

Are you good with me continuing the line you started with `custom-preamble`, and just augmenting it to have replaceable parameters?  That's my current direction, but if that isn't agreeable to you I should know before sending a pull request.  :-)

**Comment by BrunoBonacci** [comment]
sure, I still don't exactly understand what do you want to make parametrizable. You will need a templating library/function which support named placeholders `${jvm-opts}` so that you can put them in the right place, you will need support of conditionals in the templates of the different platforms and whether you wish to use the boot classloader etc.. You will need something like http://velocity.apache.org/engine/devel/ . Probably a overkill to replace 1 or 2 fields which come from your project file anyway.

Probably you have clear in mind what do you want to do, so please go ahead. I'm always up for improvement. It is probably time for a good code cleanup as well, when I forked the project it wasn't in the best state, so I might to that on the back of your PR.

**Comment by cross** [comment]
Okay.  I put in a pull request.  I note that it's very quick-and-dirty, and I'm happy to change it.  Just gets where I was looking to go, even if not via the best path.  Look forward to any feedback.

**Comment by BrunoBonacci** [comment]
hi,
I've pushed `[lein-binplus "0.6.0-SNAPSHOT"]` with a template capability. I took your idea and redesigned as the code was too messy.

this is the default template
```
:;exec java {{&jvm-opts}} -D{{project-name}}.version={{version}} -jar $0 "$@"
@echo off
java {{&win-jvm-opts}} -D{{project-name}}.version={{version}} -jar %1 "%~f0" %*
goto :eof
```
so you can specify your `:custom-preamble` with these keys.
Please give it a try and let me know if it works for you.

**Comment by cross** [comment]
Thank you.  I'm happy to accept that my/the code was too messy, and that it motivated you to improve it.  :-)

A problem, though, is that it changed the output.  As noted above, I had a number of -XX parameters, and I do not now.  I'm picking up some jvm-opts from within the plugin it seems.  If I specify only

```
bin { :name "tbx" }
```

Then the resulting binary now starts with:

```
:;exec java -server -Dfile.encoding=UTF-8 -Dtbx.version=0.1.0-SNAPSHOT -jar $0 "$@"
@echo off
java -server -Dfile.encoding=UTF-8 -Dtbx.version=0.1.0-SNAPSHOT -jar %1 "%~f0" %*
goto :eof
```

Also, a side note, I noticed that `{{jvm-opts}}` and `{{win-jvm-opts}}` have an ampersand prefix in NORMAL-TEMPLATE, but not in BOOTPATH-TEMPLATE.  Is that an oversight, or does that do something I don't understand?

**Comment by BrunoBonacci** [comment]
>  I'm happy to accept that my/the code was too messy...

Hey, I didn't say that your code was messy, but the one I've inherited from the fork.

regarding the options `-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:-OmitStackTraceInFastThrow` as I mentioned earlier this DISABLE the JIT compiler completely.

The JIT compiler turns the code, that runs frequently, into native code (which is much much faster).
So typically you should never use disable it. Leiningen uses them because typically the build process is a short lived process which doesn't take advantage of the JIT compiler. Additionally it can be useful for quick REPL sessions.
I think it was a mistake to put these options into the generated binaries in first place, however if you think they are useful for your project you can add them as `{:bin {:jvm_opts ["-XX:+TieredCompilation" "-XX:TieredStopAtLevel=1" "-XX:-OmitStackTraceInFastThrow"]}}`.

Finally `{{jvm-opts}}` are the options specified as `:jvm_opts` .  The `{{win-jvm-opts}}` is a Windows compatible version of the same. for example if you were to specify `$HOME` as part of  your `:jvm-opts`, this won't work on Windows.  `{{win-jvm-opts}}` would convert `$HOME` into`%HOME%`.

I will add a description in the README.md

**Comment by BrunoBonacci** [comment]
Hi,
I've added a section in the documentation which explains how to use the custom-preamble with the template suggestion.

https://github.com/BrunoBonacci/lein-binplus#advanced-use

I've also released and pushed the `[lein-binplus "0.6.1"]` with all the changes.

I believe this should enable you to customize the preamble to support your needs.
Could you please let me know try this version and let me know if you managed to generate a executable jar for your use-case?

**Comment by cross** [comment]
Hey Bruno.  Thanks.  I'm still tweaking with it, but I'm 99% sure this will meet my needs.  The exact jvm options I want to use and where I set them up I'll work out as I go.  I'm still curious that you're force-overridding the set of options that I was seeing.  I assume that must be from other knowledge that those are always present in leiningen ?  I understand your suggestion that they're unwanted, I just wanted to make sure that it wasn't specific to my configuration in my leiningen project.

Another thing I noted: when I looked at the [documentation for clostache](https://github.com/fhd/clostache/blob/master/README.md), I noticed that "{{" will cause certain characters to be HTML escaped.  In this context, I think you want to be using and documenting "{{{" or "{{&", to avoid that.

**Comment by cross** [comment]
Hey Bruno.  I have something working with 0.6.1.  But I'm still concerned about the changes you make based on the leiningen jvm-opts that I was seeing in my project.  For a short-lived program as mine can often be, I see the following timings (running binary 5 times from bash shell):
```
/tmp/tbx.lein-bin
total 13.21, avg  2.642
/tmp/tbx.lein-binplus
total 18.53, avg  3.706
/tmp/tbx.bootclasspath
total 10.61, avg  2.122
/tmp/tbx.custom
total 10.73, avg  2.146
/tmp/tbx.old-jvm-args-and-bootclasspath
total 7.70, avg  1.540
```

So, from the above, the code I'd started with does a start and stop in 2.64 seconds.  Switching to lein-binplus, with your overridden jvm-opts including -server, yields 3.7 seconds.  This is why I worry.  By manually overriding back to include those three -XX argments, and using the bootclasspath syntax in my custom-preamble, gets me the fasted execution time for my short-lived program test.

Let me know your thoughts.  (Thank you for the cloustache changes mentioned above.)

**Comment by BrunoBonacci** [comment]
Hi @cross,

The reason why these options were present before is because `leiningen` runs with these.
You can see here that these options are added automatically.
https://github.com/technomancy/leiningen/blob/d43fb41c64ae51bac5e3150773d4971e022dccfb/leiningen-core/src/leiningen/core/project.clj#L496

the idea is that since leiningen is a short-lived process it won't last long enough to trigger these optimizations. In fact the JIT compiler collects statistics during the Tier1 (interpreted mode) for a number of cycles before it decides whether a particular piece of code can be JIT compiled into native code.

The reason why these options ended up in your executable before was due to the fact that leiningen plugins have to add `:eval-in-leiningen true` in their `project.clj`
https://github.com/BrunoBonacci/lein-binplus/blob/master/project.clj#L14

As side effect, because the plugin is running as part of the leiningen process it inherits these options as well.

Generally, Java processes perform best in long running session (web service, databases etc), and automatically disabling the JIT compiler for everyone is (in my opinion) is a bad idea.

Now, if your executable is always short-lived, I would suggest to try with `-client` Hotspot.

```
:bin {:jvm-opts ["-client" "-Dfile.encoding=utf-8" "$JVM_OPTS" ]}}
```

This configuration tells the JVM to do optimizations which are suitable for short lived process like client applications.

If this doesn't yield good result, and your are convinced that you won't benefit from the JIT, then just add them back in your `project.clj`

```
:bin {:jvm-opts ["-client" "-Dfile.encoding=utf-8" 
                           "-XX:+TieredCompilation" 
                           "-XX:TieredStopAtLevel=1"
                           "-XX:-OmitStackTraceInFastThrow"
                           "$JVM_OPTS" ]}}
```
if you perform some measurement like the one in your last comment, i'd like to see some results just for curiosity.

Thanks for all the time you took and the feedback you sent.
Bruno

**Comment by cross** [comment]
With just the first set you suggested, I get `avg 2.144`, nearly the same as I get from no custom-premable and using `bootclasspath` (2.156), and when using the custom-preamble without overridding jvm-opts (2.156).  The full set in addition to the `-client` and others, exactly from your last example, gives me an average runtime (of the "start then exit" for this program) of 2.678.  I thought that was odd, then realized I was doing it without `bootclasspath` set to true.  I'm losing track of the number and details of the variations.  :-/

Okay.  Now I'm figuring out where things are wrong, I think.

So my first number above (with the -client example of yours without the -XX args, ~2.6 sec) was clearly using bootclasspath, whether as a flag, or within a custom-preamble I am using for many of these tests.  I confirmed that, by running again, with _only_ :jvm-opts (and :name) set within the :bin section.  That gets me 3.6 sec, nearly the same as the default of lein-binplus, which uses -server.  When using my custom-preamble which incorporates the structure learned from the "bootclasspath" option, it's much better.  But, best of all is the custom-preamble which incorporates the bootclasspath structure, and then just setting jvm-opts to just those three that leiningen had provided.  (Using just those three options from leiningen, and no other flags, I get about the same as I was getting from lein-bin, as I'd expect, ~2.6 sec).

The result I'm going to stick with, for this program, gets ~1.6 sec for the "run just to exit" test case.  That is achieved with:
```
  :bin {:name "tbx"
        :jvm-opts [ "-XX:+TieredCompilation" "-XX:TieredStopAtLevel=1" "-XX:-OmitStackTraceInFastThrow" ]
        :custom-preamble "#!/bin/sh\nexec java {{&jvm-opts}} -D{{&project-name}}.version={{&version}} -Xbootclasspath/a:$0 {{&main}} \"$@\"\n"
       }
```

**Comment by cross** [comment]
(And I've now added "-client" and "-Dfile.encoding=utf8" separately and together, which now take 1.58, at least when run with my custom-preamble.  It looks like without, trying that again now, it's 2.6-2.7.  So, I don't trust my timings very much anymore.  Too many variables.  I'm sorry that I haven't been of more help here.)

**Comment by BrunoBonacci** [comment]
That's ok, thanks again for taking the time to run these tests.
The best combination of parameters really depends on the type of workload that the JVM will have to work with, so it is very much empirical at this stage.
If it is ok for you I will close this ticket. If you have any additional query you can reopen this ticket or create another ticket. Hopefully with the new module system in Java9 we will be able to shorten the time even further.
If you are looking for shorter startup time there are a few alternative interesting project which you might want to consider.

  - [nexe](https://github.com/nexe/nexe) - If you can write your app in ClojureScript, you can then compile it to nodejs and use this project to create a native executable (platform dependant)
  - [planck](https://github.com/mfikes/planck) - A stand-alone ClojureScript REPL for macOS and Linux based on JavaScriptCore. Very fast startup. interesting alternative.
  - [pixie](https://github.com/pixie-lang/pixie) is a Clojure inspired language which runs on a native VM with JIT compiler (incredibly fast). Additional benefit is a easy access to C libraries via a built-in FFI bridge.
